pipeline {
          agent any
          stages {
                    stage('Setup Node.js') {
                        steps {
                            nodejs(nodeJSInstallationName: 'Node.js 18') { // Note the exact name here
                                sh 'node -v' // Verify the correct version is used
                                sh 'npm -v'
                            }
                        }
                    }
                    stage("Install Dependencies") {
                              steps {
                                      echo 'Installing Dependencies...'
                                        
                              }
                    }
                    stage("Test") {
                              steps {
                                     echo 'testing...'    
                              }
                    }
          }          
}
