pipeline {
          agent any
          stages {
                    stage("build") {
                              steps {
                                      echo 'building the test...'  
                              }
                    }
                    stage("test") {
                              steps {
                                     echo 'testing the test...'    
                              }
                    }
                    
}
